spring:
  profiles:
    active:
      - dev

---
server: 
  port: 7003

spring:
  profiles: dev
  application:
    name: microservice-consumer-config-clent

---
server: 
  port: 7004

spring:
  profiles: test
  application:
    name: microservice-consumer-config-clent